### ISSUE TITLE
Make a login page for a website.

### ISSUE THREAD

**Issue by aditijhaa9901** [aditijhaa9901/hello-world#2]

**Comment by aayushwadhwa1** [comment]
Can i take up this?

**Comment by Shivangi-ch** [comment]
Can i work on this?

**Comment by mitesh000790** [comment]
@aditijhaa9901 I have the best idea about login with an emoji reaction...can I work on this?

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.
